### ISSUE TITLE
Environment Install Fails

### ISSUE THREAD

**Issue by ShellHeadBash** [ibmm-unibe-ch/TemBERTure#5]
Hi,

When I try install by following the instructions (cloning, filtering and pip install -requirements.txt) I get and error when it reaches the ProDy package. From a couple of Googles it looks like the ProDy package is not compatible with Python 3.12. Is there any fix for this? 

I am on Ubuntu Desktop 24.04.1 with Python 3.12. The error message is below:

Collecting ProDy
  Using cached ProDy-2.4.1.tar.gz (21.7 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [58 lines of output]
      Collecting setuptools
        Using cached setuptools-74.1.1-py3-none-any.whl.metadata (6.7 kB)
      Collecting wheel
        Using cached wheel-0.44.0-py3-none-any.whl.metadata (2.3 kB)
      Collecting numpy<1.24,>=1.10
        Using cached numpy-1.23.5.tar.gz (10.7 MB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'error'
        error: subprocess-exited-with-error
      
        × Getting requirements to build wheel did not run successfully.
        │ exit code: 1
        ╰─> [33 lines of output]
            Traceback (most recent call last):
              File "/home/system/Software/TemBERTure/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
                main()
              File "/home/system/Software/TemBERTure/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
                json_out['return_val'] = hook(**hook_input['kwargs'])
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/home/system/Software/TemBERTure/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
                backend = _build_backend()
                          ^^^^^^^^^^^^^^^^
              File "/home/system/Software/TemBERTure/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
                obj = import_module(mod_path)
                      ^^^^^^^^^^^^^^^^^^^^^^^
              File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
                return _bootstrap._gcd_import(name[level:], package, level)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
              File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
              File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
              File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
              File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
              File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
              File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
              File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
              File "<frozen importlib._bootstrap_external>", line 995, in exec_module
              File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
              File "/tmp/pip-build-env-i753o2dn/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
                import setuptools.version
              File "/tmp/pip-build-env-i753o2dn/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
                import pkg_resources
              File "/tmp/pip-build-env-i753o2dn/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2172, in <module>
                register_finder(pkgutil.ImpImporter, find_on_path)
                                ^^^^^^^^^^^^^^^^^^^
            AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: subprocess-exited-with-error
      
      × Getting requirements to build wheel did not run successfully.
      │ exit code: 1
      ╰─> See above for output.
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by Ch-rode** [comment]
Hi @ShellHeadBash, thanks for using TemBERTure! Sorry for the late replay, I was offline.
In the [README](https://github.com/ibmm-unibe-ch/TemBERTure#2-install-the-python-env-python-3918) I wrote than the env uses 3.9.18. I reccomand using this python version.
