### ISSUE TITLE
offline mode

### ISSUE THREAD

**Issue by xing-he529** [ibmm-unibe-ch/TemBERTure#6]
Hello, I have followed your example, and  got an error like this :

Traceback (most recent call last):
  File "/home/xinghe/mambaforge/envs/temberture/lib/python3.9/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/home/xinghe/mambaforge/envs/temberture/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/home/xinghe/mambaforge/envs/temberture/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

and then, I downloaded the Rostlab/prot_bert_bfd in my directory, containing the following files:
config.json  pytorch_model.bin  special_tokens_map.json  tokenizer_config.json  vocab.txt
This time, when I run the Python script, there's no error or output message.

Can you give me some help, on how I can use TemBERTure in offline mode? Thank you

**Comment by Ch-rode** [comment]
Dear @xing-he529,
Thank you for using TemBERTure! Could you please provide more details about the error you're encountering? It appears to be related to a connection issue on your end. If you've already downloaded the Rostlab/prot-bert weights and this repository, you should be able to use TemBERTure offline.

**Comment by xing-he529** [comment]
> Dear @xing-he529, Thank you for using TemBERTure! Could you please provide more details about the error you're encountering? It appears to be related to a connection issue on your end. If you've already downloaded the Rostlab/prot-bert weights and this repository, you should be able to use TemBERTure offline.


Here's the full messages:
Traceback (most recent call last):
  File "/home/xinghe/mambaforge/envs/temberture/lib/python3.9/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/home/xinghe/mambaforge/envs/temberture/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/home/xinghe/mambaforge/envs/temberture/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xinghe/mambaforge/envs/temberture/lib/python3.9/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/home/xinghe/mambaforge/envs/temberture/lib/python3.9/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/home/xinghe/mambaforge/envs/temberture/lib/python3.9/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/home/xinghe/mambaforge/envs/temberture/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "/home/xinghe/mambaforge/envs/temberture/lib/python3.9/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "/home/xinghe/mambaforge/envs/temberture/lib/python3.9/site-packages/urllib3/connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f5f6e237670>: Failed to establish a new connection: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xinghe/mambaforge/envs/temberture/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/xinghe/mambaforge/envs/temberture/lib/python3.9/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/home/xinghe/mambaforge/envs/temberture/lib/python3.9/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Rostlab/prot_bert_bfd/resolve/main/config.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5f6e237670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xinghe/mambaforge/envs/temberture/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1238, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/home/xinghe/mambaforge/envs/temberture/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/xinghe/mambaforge/envs/temberture/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1631, in get_hf_file_metadata
    r = _request_wrapper(
  File "/home/xinghe/mambaforge/envs/temberture/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 385, in _request_wrapper
    response = _request_wrapper(
  File "/home/xinghe/mambaforge/envs/temberture/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 408, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "/home/xinghe/mambaforge/envs/temberture/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/xinghe/mambaforge/envs/temberture/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/xinghe/mambaforge/envs/temberture/lib/python3.9/site-packages/huggingface_hub/utils/_http.py", line 67, in send
    return super().send(request, *args, **kwargs)
  File "/home/xinghe/mambaforge/envs/temberture/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Rostlab/prot_bert_bfd/resolve/main/config.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5f6e237670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: aa1e16d5-7a58-4717-870c-39ebd08aac00)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xinghe/mambaforge/envs/temberture/lib/python3.9/site-packages/transformers/utils/hub.py", line 430, in cached_file
    resolved_file = hf_hub_download(
  File "/home/xinghe/mambaforge/envs/temberture/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/xinghe/mambaforge/envs/temberture/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1371, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/share/TemBERTure/test.py", line 4, in <module>
    model_replica1 = TemBERTure(
  File "/home/share/TemBERTure/temBERTure.py", line 29, in __init__
    self.model = BertAdapterModel.from_pretrained(model_name) 
  File "/home/xinghe/mambaforge/envs/temberture/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2760, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/home/xinghe/mambaforge/envs/temberture/lib/python3.9/site-packages/transformers/configuration_utils.py", line 593, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/xinghe/mambaforge/envs/temberture/lib/python3.9/site-packages/transformers/configuration_utils.py", line 622, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/xinghe/mambaforge/envs/temberture/lib/python3.9/site-packages/transformers/configuration_utils.py", line 677, in _get_config_dict
    resolved_config_file = cached_file(
  File "/home/xinghe/mambaforge/envs/temberture/lib/python3.9/site-packages/transformers/utils/hub.py", line 470, in cached_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like Rostlab/prot_bert_bfd is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.





Yes, you are right, it has internet connection issues. So I'm wondering how can I use TemBERTure offline。
Now I download the Rostlab/prot_bert_bfd directory, and run this code:
model_replica1 = TemBERTure(
    adapter_path='./temBERTure_TM/replica1/',  # Path to the adapter for replica 1
    device='cuda',                                        # Device to run the model on
    batch_size=16,                                        # Batch size for inference
    task='regression'                                     # Task type
... )


After running, there is no feedback, no errors, and no output.

**Comment by Ch-rode** [comment]
You need to open the `temBERTure.py` file and, at line 28, replace the `model_name` path with the path where you have saved the `Rostlab/prot_bert_bfd model`.

```    def __init__(self, adapter_path, model_name=**local_prot_bert_bfd_directory**,batch_size=16, device='cuda', task = 'regression'):```
